### PR TITLE
Prepare 1.5.0 release

### PR DESCRIPTION
**Pull request by stipsan**
@Arcanemagus since master is a protected branch I'm doing this as a PR.

### CODE REVIEW

**Comment by stipsan** [comment]
Release draft is ready to be published once this is merged: https://github.com/AtomLinter/linter-phpmd/releases/edit/untagged-bbcb38f3cbd886098fcb

**Comment by Arcanemagus** [comment]
Ah ha, really need to get publishing from CI figured out and working. I'll just do a signed release manually then.

**Comment by Arcanemagus** [comment]
There we go, published :wink: :tada:

**Comment by stipsan** [comment]
Woohoo! 💃

**Pull request closed without merging**
