### PR TITLE
fix: support v2 Linter API

### LINKED ISSUE #129: Support v2 Linter API
In the [v2.3.0 release](https://github.com/steelbrain/linter/releases/tag/v2.3.0) of `linter` support for the v1 API was removed, breaking semver. This means that this provider is no longer supported by the current version of `linter`.

To get this provider working again it will need to be upgrade to the v2 API, a guide for accomplishing that can be found here: [Upgrading to Standard Linter v2](https://github.com/steelbrain/linter/blob/v2.3.0/docs/guides/upgrading-to-standard-linter-v2.md).

Until this is fixed in order to use this provider you will need to downgrade to the last version of `linter` that supports the v1 API, you can do this with `apm install linter@2.2.0`.

### PR DESCRIPTION
**Pull request by vzamanillo**
Fixes #129

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Hah!

I have almost the exact same thing locally, was getting #132 resolved before I pushed it up though 🤣.

It looks like there is an issue with the CI configuration right now, will be getting that fixed.

**Comment by Arcanemagus** [comment]
Yeah, it's because that's now a secure value so it isn't exposed on builds for PRs from external forks. Need to guard that so it doesn't attempt to set that if it's empty.

**Comment by Arcanemagus** [comment]
Okay, rebasing on `master` should fix your build. 🙏

**Comment by Arcanemagus** [comment]
I'm not sure how you rebased this, it seems like a merge of some sort? You should be able to make sure your `master` branch is current, then do `git rebase master` while on this branch.

**Comment by vzamanillo** [comment]
> I'm not sure how you rebased this, it seems like a merge of some sort? You should be able to make sure your `master` branch is current, then do `git rebase master` while on this branch.

hmmm, let me see

**Comment by Arcanemagus** [comment]
I'm not sure what's wrong with Travis CI, but since the specs are passing in AppVeyor this should be good to merge so I'm going to override it instead of having you try to work through it's issue.

**Comment by vzamanillo** [comment]
> I'm not sure what's wrong with Travis CI, but since the specs are passing in AppVeyor this should be good to merge so I'm going to override it instead of having you try to work through it's issue.

I was looking at https://github.com/travis-ci/travis-ci/issues/10179

**Pull request merged**
